In [1]:
# Exp.no:5
# Aim:To perform creation of arrays using numpy.
# Name:Vedanti B. Tayade
# Roll no:65
# Sec:B
# Sub:ET1
# Date:21/08/2025

# To perform creation os arrays using numpy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])

In [4]:
print(arr1)

[1 2 3 4]


In [5]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
arr3 = np.array([1,2,3],dtype=float)
arr4 = np.array([1,2,3],dtype=np.int32)

In [7]:
arr3

array([1., 2., 3.])

# Creating 1D Array using numpy

In [8]:
a1 = np.array([10,20,30,40,50])

In [9]:
a1

array([10, 20, 30, 40, 50])

# Creating 2D Array using numpy

In [10]:
a2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [11]:
a2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

# Creating 3D Array using numpy

In [12]:
a3=np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])

In [13]:
a3

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150]]])